# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [1]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 13.5 ms, sys: 4.26 ms, total: 17.8 ms
Wall time: 17.9 ms
CPU times: user 587 ms, sys: 169 ms, total: 756 ms
Wall time: 757 ms


### Exercício 2

In [2]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[5:8] = 0
arr

array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9])

### Exercício 3

In [4]:
# Crie um array de 3 dimensões e imprima a dimensão 1 
import numpy as np
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [5]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

### Exercício 4

In [6]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# Imprima os elementos da terceira linha da matriz
arr2d[2]

array([7, 8, 9])

In [8]:
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

### Exercício 5

In [9]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Exercício 6

In [11]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [12]:
for x, y, c in zip(xarr, yarr, cond):
    print(x, y, c)

1.1 2.1 True
1.2 2.2 False
1.3 2.3 True
1.4 2.4 True
1.5 2.5 False


In [13]:
resultado = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
resultado

[1.1, 2.2, 1.3, 1.4, 2.5]

### Exercício 7

In [14]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B
A = np.arange(10)
print(A)
np.save('array_a', A)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
B = np.load('array_a.npy')
print(B)

[0 1 2 3 4 5 6 7 8 9]


### Exercício 8

In [16]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

In [17]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

### Exercício 9

In [18]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [19]:
data = resp.json()
data[0]['title']

'Slicing columns with mixed types <str>,<int> fails with ValueError'

In [20]:
issues = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])
issues

number                                              title  \
0    20975  Slicing columns with mixed types <str>,<int> f...   
1    20974  BUG: Fix drop_duplicates failure when DataFram...   
2    20970            performance when "combining" categories   
3    20969        Getting a ... in my CSV when using to_csv()   
4    20968                         Sharey keyword for boxplot   
5    20967   Column can be extended beyond DataFrame's length   
6    20966             BUG: Fix wrong khash method definition   
7    20965  BUG: Fix combine_first converts other columns ...   
8    20964  BUG: Index with integer data and datetime64[ns...   
9    20962  df.rank() has different behavior for python2 a...   
10   20960  DOC: add reshaping visuals to the docs (Reshap...   
11   20958  Using apply on a grouper works only if done af...   
12   20956  ENH: Return DatetimeIndex or TimedeltaIndex bi...   
13   20955  Building documentation fails with `ImportError...   
14   20954  Correlation inconsistencies between Series and...   
15   20951  Addressing multiindex raises TypeError if indi...   
16   20948  Indexing DataFrame with DateOffset is nearly i...   
17   20947        Allow drop bins when using the cut function   
18   20945  Data is mismatched with labels after stack wit...   
19   20944                       Drop rows based on condition   
20   20943  pd.read_sql does not handle queries that retur...   
21   20940                       unclear error with  read_sas   
22   20937  BUG: Series(DTI/TDI) loses the frequency infor...   
23   20936  __new__() missing 1 required positional argume...   
24   20932  API: expose `axis` keyword in pandas.core.algo...   
25   20930  DOC: Index.get_loc Cannot Accept List-like Tol...   
26   20928             Added script to fetch wheels [ci skip]   
27   20927  read_sas OverflowError: int too big to convert...   
28   20926   BLD: Lint for invalid files in wheels / packages   
29   20925  Series.reset_index(level_name, drop=True) acce...   

                                               labels state  
0                                                  []  open  
1   [{'id': 76811, 'url': 'https://api.github.com/...  open  
2   [{'id': 78527356, 'url': 'https://api.github.c...  open  
3                                                  []  open  
4                                                  []  open  
5                                                  []  open  
6   [{'id': 76811, 'url': 'https://api.github.com/...  open  
7   [{'id': 76811, 'url': 'https://api.github.com/...  open  
8                                                  []  open  
9                                                  []  open  
10  [{'id': 134699, 'url': 'https://api.github.com...  open  
11  [{'id': 76811, 'url': 'https://api.github.com/...  open  
12  [{'id': 49597148, 'url': 'https://api.github.c...  open  
13                                                 []  open  
14                                                 []  open  
15                                                 []  open  
16                                                 []  open  
17  [{'id': 76812, 'url': 'https://api.github.com/...  open  
18                                                 []  open  
19                                                 []  open  
20                                                 []  open  
21                                                 []  open  
22                                                 []  open  
23                                                 []  open  
24  [{'id': 35818298, 'url': 'https://api.github.c...  open  
25                                                 []  open  
26  [{'id': 131473665, 'url': 'https://api.github....  open  
27                                                 []  open  
28  [{'id': 129350, 'url': 'https://api.github.com...  open  
29  [{'id': 42670965, 'url': 'https://api.github.c...  open

### Exercício 10

In [21]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas
import sqlite3
import pandas as pd
query = """
CREATE TABLE TESTE
(Cidade VARCHAR(20), 
 Estado VARCHAR(20),
 taxa REAL,        
 Impostos INTEGER
);"""
con = sqlite3.connect('dsa.db')
con.execute(query)
con.commit()

In [22]:
data = [('Natal', 'Rio Grande do Norte', 1.25, 6),
        ('Recife', 'Pernambuco', 2.6, 3),
        ('Londrina', 'Paraná', 1.7, 5)]
stmt = "INSERT INTO TESTE VALUES(?, ?, ?, ?)"
con.executemany(stmt, data)
con.commit()

In [23]:
cursor = con.execute('select * from teste')
rows = cursor.fetchall()
rows

[('Natal', 'Rio Grande do Norte', 1.25, 6),
 ('Recife', 'Pernambuco', 2.6, 3),
 ('Londrina', 'Paraná', 1.7, 5)]

In [24]:
cursor.description
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

Cidade               Estado  taxa  Impostos
0     Natal  Rio Grande do Norte  1.25         6
1    Recife           Pernambuco  2.60         3
2  Londrina               Paraná  1.70         5

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>